# Generated by Django 3.2.9 on 2021-11-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True)),
                ('parent', models.ManyToManyField(blank=True, related_name='_ug_group_parent_+', to='ug.Group')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('display_name', models.CharField(max_length=254)),
                ('groups', models.ManyToManyField(to='ug.Group')),
            ],
        ),
    ]
